### ISSUE TITLE
Gradle Sync Issue

### ISSUE THREAD

**Issue by hueyenclave** [googlecodelabs/android-dynamic-features#22] opened 2019-12-23 07:40 UTC
Hi guys,

Following guide steps on Codelab, I cloned project and got issue when open in Android Studio. Please advise

**Sync Error:**
-
> ERROR: The specified Gradle distribution 'https://services.gradle.org/distributions/gradle-5.1.1-all.zip' does not appear to contain a Gradle distribution.

**Execute gradle.bat build command**
-

> Exception in thread "main" java.lang.NullPointerException
>         at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:38)
>         at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:26)
>         at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
>         at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

Thanks,
Huey

**Comment by pfmaggi** [comment] 2019-12-30 11:58
Thanks for reporting this.
I'm closing this issue because I cannot reproduce it in this codelab.

You may have a corrupted download of the `gradle-5.1.1-all.zip` file. You may try re-downloading it or start from a fresh copy of this repository.

Please open a new issue if you still encounter this issue.

**Closed as completed by pfmaggi** 2019-12-30 11:58 UTC
